name: Playwright scheduled tests

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes (UTC)
  workflow_dispatch:         # allow manual runs too

permissions:
  contents: read

# Avoid overlapping runs if a suite sometimes exceeds 10 minutes
concurrency:
  group: scheduled-playwright
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
      # CI=true is set by GitHub Actions automatically -> your config uses workers: 1 and retries: 2 on CI
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # Cache Playwright browser binaries
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Do NOT pass --reporter or --workers here; your playwright.config controls that.
      # Projects (chromium/firefox/webkit), retries on CI, trace on first retry, html reporter—all from config.
      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7

      # Traces will exist only for retried failures (trace: 'on-first-retry')
      - name: Upload traces (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: traces
          path: test-results
          retention-days: 7
